### ISSUE TITLE
Improve performance of ZydisGetAccessedFlagsByAction

### ISSUE THREAD

**Issue by flobernd** [zyantific/zydis#150]
The performance of the function should be improved.

### Possible solution:

- Have separate flag fields in the `ZydisDecodedInstruction` for each kind of flag access (read, write, cond_read, cond_write)
- Each flag field should be of type `ZydisU32` and access bits should be set according to the `RFLAGS` register of the CPU

### Tasks:

- [x] Modify InstructionEditor to generate optimized tables for this szenario
- [x] Check performance difference in comparison to the current build
- [x] Check binary size difference in comparison to the current build (only about 1KiB larger)
- [x] Adjust `ZydisDecoder`
- [x] Mark the current flags property as deprecated (keep both fields for now to ensure backwards compatibility)
  - [ ] Move the `flags_read` and `flags_written` fields inside the `accessed_flags` struct
  - [ ] Refactor `accessed_flags[].action` -> `accessed_flags.by_action[]`
  - [x] Change `ZydisCPUFlag` enum to flag defines and change the values to to reflect the native `FLAGS/EFLAGS/RFLAGS` bits

**Comment by athre0z** [comment]
On that note, I think we should merge the `SET_0` and `SET_1` fields into just being `WRITE` as well because without any other semantics it is hardly imaginable that the ability to differentiate between them will ever be helpful to any user but would require two additional flag ints.

**Comment by flobernd** [comment]
First progress: https://github.com/zyantific/zydis/commit/48d0b33bca88a73be38942ccc95ca09454ace24d
